### ISSUE TITLE
Feature: Camera Movement

### ISSUE THREAD

**Issue by n1ght4ngel19** [n1ght4ngel19/electronic-gruntz#2]
Create all the required camera manipulation features:

- [x] 1. Zooming in close and out to the bounds of the map
- [x] 2. Moving the view by holding the pointer near one of the edges of the screen
- [x] 3. Moving the view with the arrow keys
